### ISSUE TITLE
[Windows Bug] Open file in explorer fails if space is in the filepath

### ISSUE THREAD

**Issue by Loran425** [TagStudioDev/TagStudio#120]
## Expected Behavior
`Open file in explorer` should open a the file explorer at the file path

## Current Behavior
If the file path contains spaces explorer opens to another window (Documents on my machine)

## Possible Solution
Check filepath for whitespace when utilizing `open file in explorer` 
Only on windows, wrap the path with quotes to open the correct folder

## Steps to Reproduce
1. Create a library in a folder with whitespace in the path
2. Right Click on a file
3. Select `Open file in explorer`
4. Check what folder it opened

**Comment by filip-patafta** [comment]
I've fixed the issue with opening files in explorer when the file path contains spaces. The problem was caused by not properly handling file paths with spaces on Windows. I've modified the code to wrap the file path in quotes, which resolves the issue. I've also tested the fix locally and it works as expected.

I'll push the changes to the repository shortly.
