### ISSUE TITLE
inconsistent behaviour of `Favourite` and `Archived` tags 

### ISSUE THREAD

**Issue by yedpodtrzitko** [TagStudioDev/TagStudio#138]
- when I click the star icon on item, it adds `Favorite` into "Meta Tags" field

- I can assign the tag "Favorite" into "Tags" field manually

- I click the star icon again to remove the tag, I would assume it will remove it only from "Meta Tags", but it gets removed from "Tags" as well.

This feels inconsistent. What is the intended behaviour here?

**Comment by yedpodtrzitko** [comment]
ok, but in that case I'd expect the same behaviour when favoriting the item via the badge icon, ie. the tag will be added not only in Meta Tags, but also tags

**Comment by CyanVoxel** [comment]
Here's the perspective I'm looking at it from: An entry is marked as a Favorite if it contains a Favorite tag, and isn't marked as a Favorite if it does not contain this tag. When turning that functionality into a toggle, then toggling it as a Favorite will meet the minimum requirements by adding a Favorite tag, which at the time of writing defaults to the Meta Tag group. Conversely, if you were to toggle the entry as not a Favorite, you would need to meet the requirements of making sure that the entry no longer contains a Favorite tag. Due to being able to have the same tag under multiple groups, this means that there could be multiple favorite tags that need to be removed. So functionally the Favorite toggle operates on the idea of "meet the requirements of making the entry a Favorite" and "meet the requirements of removing the entry as a Favorite", while aligning itself with how tags and field groups currently work.

There are changed planned to how fields operate and are created, especially when it comes to tags, but this example should still hold true. If anything, in the future tags being in a certain "group" will have more of an hierarchical impact than just a visual one alone.
