### ISSUE TITLE
Ressources on 'taggable tags'

### ISSUE THREAD

**Issue by xvrdm** [TagStudioDev/TagStudio#143]
Thank you for making this project open-source! It explores a very interesting problem space!

Do you have resources you could share on _"tag composition, or “taggable tags”"_ (article, HN discussion...) ?
This was the part of the video I found most interesting but I cannot find any more info about it.

I think you only mentionned https://en.wikipedia.org/wiki/Attribute%E2%80%93value_system .

**Comment by Icosahunter** [comment]
I don't know of any literature on the exact same system used in TagStudio, but the problem it seeks to solve is closely related to [software ontologies](https://en.wikipedia.org/wiki/Ontology_(information_science)) and many such ontology structures are reminiscent of TagStudio tags (usually with more complex structure since the goal is more involved than just organizing for searching). The way it works in TagStudio is basically like the hierarchical system CyanVoxel discussed at the beginning of his video, except that tags can have multiple parents. You can visualize it as a [directed (probably acyclic) graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph), where the nodes are tags, and the arrows point from parent tags (usually more general concepts) to the child tags (usually more specific concepts). So you might have a VideoGame tag and a Nintendo tag, and a Mario tag that inherits from both. In the video he presents the direct parent tags as subtags, as they are essentially tagging the tags, this is another way to visualize it. Wikipedia also has a page on [tags](https://en.wikipedia.org/wiki/Tag_(metadata)) which touches on it's connection to ontologies and has at least one common link in the see-also: [concept maps](https://en.wikipedia.org/wiki/Concept_map).

**Comment by CyanVoxel** [comment]
> Thank you for making this project open-source! It explores a very interesting problem space!
> 
> Do you have resources you could share on _"tag composition, or “taggable tags”"_ (article, HN discussion...) ? This was the part of the video I found most interesting but I cannot find any more info about it.
> 
> I think you only mentionned https://en.wikipedia.org/wiki/Attribute%E2%80%93value_system .

@Icosahunter has a better reply than I'll be able to come up with 😁 A lot of what I've/we've been developing for the taggable tags is both very new and very old, depending on how you look at it. The idea of composing and inheriting "tags" for data might not be done very much in software programs, but the principles of composition and inheritance have been around for ages. The [Attribute-Value](https://en.wikipedia.org/wiki/Attribute%E2%80%93value_system) system was the closest existing knowledge framework that I could find at the time that could describe what I was trying to do, but there are surely more accurate ways to describe the system. Icosahunter was right on the money with bringing up [directed acyclic graphs](https://en.wikipedia.org/wiki/Directed_acyclic_graph) as well, since that's exactly the structure the tags take on once connected (or at least, they *should* be acyclic). And as the project grows we're also constantly reevaluating approaches and use cases while researching existing ontologies and ideas that may already describe what we want to accomplish. [RDF triples](https://en.wikipedia.org/wiki/Semantic_triple), for example, is one area we keep looking into as a potential addition/replacement of certain tag relationships.

**Comment by xvrdm** [comment]
Thanks a lot for these comments!
