### ISSUE TITLE
All-in-one please-download-and-run-thank-you "easy mode" script

### ISSUE THREAD

**Issue by ShadowJonathan** [TagStudioDev/TagStudio#25]
I'm seeing a lot of people in the discord asking for help with installation instructions, I think we should have a simple `easy_run.bat` script or the likes that would;
1. Check the installed python version(s), pick a compatible one, or;
  - Install a compatible python version (maybe after "press Y to install python")
2. Create a venv, and install dependencies inside of it, or just verify its there
3. Launch the program

This script could be hailed with a CMD `./easy_run.bat`, or a double-click.

----

This script should be entirely temporary to the alpha stage and should be removed once we start doing packaged releases (releases with .exe binaries/installs bundled with them).

**Comment by OleMortensen8** [comment]
[ShadowJonathan](https://github.com/ShadowJonathan) like the #10 but for windows while we debug? sure.

**Comment by ShadowJonathan** [comment]
More or less, but one that either prompts to or auto-installs Python (with a Y/N prompt) for the user

**Comment by Wuffli** [comment]
I think this will make sense in particular as soon as we'll have a version that we want more people to test.

**Comment by lynphan** [comment]
I looked into it a bit more after our discussion on discord (Hi!, it's sheepbunmonster 👋 ), and it does appear like `winget` is the way to go. It's the native package manager for Windows so it should be available on anything with Windows 10/11, and it'll let us install older versions too (since TagStudio only works on versions earlier than Python 3.10) right now. 

![image](https://github.com/CyanVoxel/TagStudio/assets/22333215/4692e5c6-1798-4b45-9f9a-8ecc822eee72)

In the batch script itself, you'll probably need to get elevated priviledges, then run something along the lines of `winget install Python.Python -v 3.10`. And then you should be able to run the `venv` commands (though we'll likely need to account for which python version is called). There might also be issues with needing to restart the shell to get the updated PATH from the new Python version, which was an issue I used to run into (though it might not be an issue here).

Hope that helps with some of the Python installation stuff!

**Comment by neilfranci** [comment]
> I looked into it a bit more after our discussion on discord (Hi!, it's sheep 👋 ), and it does appear like `winget` is the way to go. It's the native package manager for Windows so it should be available on anything with Windows ~10~/11, and it'll let us install older versions too (since TagStudio only works on versions earlier than Python 3.10) right now. (Edit: Turns out winget is only available on windows 11 and later versions of windows 10, which I ran into when I was setting up my dev environment. Might end up being a situation where a user might still need to install something manually).
> 
> ![image](https://private-user-images.githubusercontent.com/22333215/324983830-4692e5c6-1798-4b45-9f9a-8ecc822eee72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDEwMjYsIm5iZiI6MTcxMzk0MDcyNiwicGF0aCI6Ii8yMjMzMzIxNS8zMjQ5ODM4MzAtNDY5MmU1YzYtMTc5OC00YjQ1LTlmOWEtOGVjYzgyMmVlZTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA2Mzg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMGMyN2M2Mzk1ZDJjMGVjMDExZTY2MzQ0N2NhMTczYjQ1OWNhMWIxYmYyMDFkYWFhM2ZjZTgyNDEyODI4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OH3bBcwSHUHxXQWP5CTiS_aAAkEr26bzzYykweGGtHo)
> 
> In the batch script itself, you'll probably need to get elevated priviledges, then run something along the lines of `winget install Python.Python -v 3.10`. And then you should be able to run the `venv` commands (though we'll likely need to account for which python version is called). There might also be issues with needing to restart the shell to get the updated PATH from the new Python version, which was an issue I used to run into (though it might not be an issue here).
> 
> Hope that helps with some of the Python installation stuff!

Can we have a Python check before installing anything?
And then check if the user wants to use winget or scoop or choco?
Cause I don't use Winget, I use scoop.sh, some use choco. Installing something that is already installed is a bit extra.

**Comment by LunaLorea** [comment]
Have you looked into PyInstaller?

**Comment by ShadowJonathan** [comment]
yes, but iirc that one packages an application for distribution, right?

this is for quick-n-dirty "run from source" for anyone who doesn't have previous development experience, we could use pyinstaller in the CI for tagging release builds with it, so people can download those

**Comment by Thesacraft** [comment]
Hi,
I looked into packaging this with pyinstaller(don't know if its to early for it). I got it working as a exe with a console. I used auto-py-to-exe (python package) that is build on pyinstaller and just provides a ui for generating the command to build it. The only concern that i have about that is that the outputet exe is unsigned and if someone downloads it they get that popup from windows smart screen.... But the following comand worked for me to build it
```
pyinstaller --noconfirm --onefile --console --add-data "tagstudio/resources;resources/" --paths "tagstudio"  "tagstudio/tagstudio.py"
```
I build it as a console application because windows defender complains if i build it as a window application. 
I also think that winget can be run without priviliges but not sure about that right now.

**Comment by Thesacraft** [comment]
Update:
As the tagstudio.py got renamed here is an updated command that now also includes the icon to package into the exe:
`pyinstaller --noconfirm --onefile --console --icon "tagstudio/resources/icon.ico" --add-data "tagstudio/resources;resources/" --paths "tagstudio"  "tagstudio/tag_studio.py"`

**Comment by Loran425** [comment]
Executables have been added to release [v9.2.0](https://github.com/TagStudioDev/TagStudio/releases/tag/v9.2.0)

**Comment by CyanVoxel** [comment]
@o-data [Discord invite link](https://discord.gg/VdJPzukGxN)
