### ISSUE TITLE
[Feature Request]: Ai Tagging 

### ISSUE THREAD

**Issue by ThesiiNCey** [TagStudioDev/TagStudio#326]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

I have write an Ai Tagging Script for my Local Images in Python thats using https://huggingface.co/SmilingWolf/wd-v1-4-swinv2-tagger-v2

Can you build a Feature Like this in ? 

Or can it help to share my Script ?

### Solution

Add an Image Interogator to Tag Images Automaticly Like in Stable Diffusion ( WD Tagger )

**Comment by Qronikarz** [comment]
Is this issue about general AI tagging? Or just tagging from one source (like Stable Diffusion tags)?

If the first case then it could be implemented like in Spacedrive: https://www.spacedrive.com/blog/alpha-zero-two-release
It used AI to automatically tag images using one of the models. Though the tags that were created this way had a different name so that it is known that they were applied automatically.

This model would be especially useful: https://github.com/xinyu1205/recognize-anything
Though I have no idea how hard it would be to implement it, or what does it need and how much space it would take.

**Comment by CyanVoxel** [comment]
This is something I am not interested in adding into the program, as I explain in the [readme](https://github.com/TagStudioDev/TagStudio?tab=readme-ov-file#features-that-will-not-be-added). However, this could be done by someone else in the future as a [plugin](https://github.com/TagStudioDev/TagStudio/issues/47).
