### ISSUE TITLE
[Feature Request]: Make gifs animate in app

### ISSUE THREAD

**Issue by Thecreatre** [TagStudioDev/TagStudio#338]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

its  as simple  as  the title make gifs work  in app

(also Apng too but it might work allready and i wouldn't know cause i don't have any apps other than a decomp* thing for Apngs)

*(splits off the other images hidden in the file)

### Solution

make gifs (and maybe Apngs if they  didn't work already)  work in tag studio

(also maybe get  it  to work for those cached thumbnails upcoming feature probably things, but its not as  required as  just making it work  in  the tiny viewer thing)

**Comment by CyanVoxel** [comment]
GIF previews are currently operational on the [thumbnails](https://github.com/TagStudioDev/TagStudio/tree/thumbnails) branch, which will be merged into the upcoming 9.4 release

**Comment by Thecreatre** [comment]
i see, (didnt know that even existed)

**Comment by Thecreatre** [comment]
I'll probably just keep using the main branch tbh, its not too annoying  for me, at least if i keep open a instance of photos so that #339 doesn't lock up photos again

**Comment by CyanVoxel** [comment]
> I'll probably just keep using the main branch tbh, its not too annoying for me, at least if i keep open a instance of photos so that #339 doesn't lock up photos again

I'd recommend the same, if anything keep an eye out for when I eventually make a PR and it gets merged into the `Alpha-9.4` branch, although by then I may make a pre-release for 9.4 based on the state of that branch.

Also to address APNG playback, I've done some initial testing to see if it would be immediately supported by my GIF playback implementation but it looks like it isn't natively supported by Qt. That being said I may be able to just convert the APNG file to a GIF on the fly and plug it into the playback system. Animated WEBPs are also easy to get working, although I'd rather develop a way to distinguish still from animated WEBP files in the preview pane before adding that in due to some UI quirks.

**Comment by Thecreatre** [comment]
ah i see

**Comment by BPplays** [comment]
@CyanVoxel i feel like converting APNG to WEBP instead of GIF is probably a better idea

**Comment by CyanVoxel** [comment]
GIF playback added in #390
