### ISSUE TITLE
[Feature Request]: nix flake formatter output

### ISSUE THREAD

**Issue by Familex** [TagStudioDev/TagStudio#433]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

`outputs.formatter.<system>` output used by `nix fmt` and formats all `.nix` files in project. I believe, the `flake.nix` is manually formatted at this point...

### Solution

https://github.com/NixOS/nixfmt can be used

**Comment by zierf** [comment]
Just checked, I have _nix lsp_ (`nil`) and _formatter_ (`nixpkgs-fmt`) installed. 

Using it on my provided Flake in #200 doesn't change anything in the file, it "is already formatted". And it doesn't seem too far off what @xarvex was using when we fixed video playback on Nix and enabled hardware acceleration (#417). I triggered the formatter and it was changing nothing (though I was expecting many little changes).

However, the formatter has some very strong opinions about line breaks near curly braces (e.g. after `let` statements) and doesn't care at all about those when merging lists `([ ]) ++ ([ ])`.
I've seen better, the formatter is far from _rustfmt_.

I simply chose one at the time and I don't have any strong preferences. But this topic seems to provide an abundance of choices for different alternatives instead of a common standard tool.

I'm still rather open to this, but ideally it should be __simple__, __automatic__ and __available for most code editors__ out there.

**Comment by Familex** [comment]
@zierf `nix fmt` don't interact with code editor. It is just a command to run before commit.

I don't think it makes much difference which package we should use (because there is only one file). I'm simply suggesting to pin something.

I use alejandra as default nix formatter and it messes file up.

**Comment by xarvex** [comment]
Thus far I have been using `nixfmt-rfc-style` as the formatter, as that is the official formatter used in nixpkgs. I can totally go ahead and expose the formatter attribute, I had forgotten about that.

**Comment by xarvex** [comment]
Ouch, was a bit of a diff after that `nix fmt`, I think at some point I had removed the formatter from my PATH from my Nix configuration as I was putting all development tools into shells. But, at least the problem won't occur again. :sweat_smile:

**Comment by Sigmanificient** [comment]
`nixpkgs-fmt` is the legacy formatter from the first formatting RFC of nixpkgs. We should use `nixfmt-rfc-style`

**Comment by Sigmanificient** [comment]
@xarvex
