### ISSUE TITLE
[Feature Request]: Redirect tagstud.io to somewhere

### ISSUE THREAD

**Issue by dev-ardi** [TagStudioDev/TagStudio#518]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

Right now tagstud.io is not getting http traffic. 

### Solution

Either redirect it to the github or to the docs page

**Comment by Nginearing** [comment]
May I ask, why?

**Comment by Nginearing** [comment]
> Right now it just says that it doesn't exist

It's just not pointed to any page yet. No one is trying to access tagstud.io anyway, If you looked on the gihtub the only url you'd access is docs.tagstud.io, so this should be marked as wontfix.

**Comment by Computerdores** [comment]
> May I ask, why?

It would for the time being provide a shorter URL to type if one doesn't have a link handy to click on.
Also, what's the harm? It's quick to do and the domain isn't being used for anything (although I would make it return a 307, to be clear that it is temporary and so that no one links to tagstud.io instead of docs.tagstud.io).

**Comment by Computerdores** [comment]
Closing this as [tagstud.io](http://tagstud.io) currently redirects to the Github as requested
