### ISSUE TITLE
[Feature Request]: Make the create tag panel have empty tag name field

### ISSUE THREAD

**Issue by Cool-Game-Dev** [TagStudioDev/TagStudio#591]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

Remove the need to delete the "New Tag" text in the create tag window. 

### Solution

Replace the "New Tag" default text with a greyed out version that only appears if the name is empty. This would also fill an empty tag name with "New Tag".

### Alternatives

Select the text automatically, this could cause confusion with consistency.

**Comment by Cool-Game-Dev** [comment]
#592

**Comment by Cool-Game-Dev** [comment]
Waiting to be merged in #592

**Comment by VasigaranAndAngel** [comment]
> This would also fill an empty tag name with "New Tag".

placeholder text is meant to show an example or explanation for the input right? automatically creating a new tag named "New Tag" when pressing done with an empty name isn't what i would expect.

currently the backend doesn't support multiple tags with same name. so attempting this will raise an error. that error is suppressed also (only shown in debug). which will cause the user to lose the new tag creation setup (Shorthand, Aliases, etc.).

my suggestion would be to block the user from pressing done with an empty tag name and instead notify them without closing the `BuildTagPanel` window.

**Comment by CyanVoxel** [comment]
> placeholder text is meant to show an example or explanation for the input right? automatically creating a new tag named "New Tag" when pressing done with an empty name isn't what i would expect.

The old behavior is to pre-populate the name field with "New Tag" which has the same effect of leaving the placeholder text alone and creating a new tag with no name. While a tag with a blank name isn't strictly bad from a data design perspective, it creates a confusing default behavior for new tags when going back to view the list of tags available in your library (i.e. blank boxes in the list). If a user neglects to fill out a name for a tag, then they probably wouldn't be too surprised if they see a tag named "New Tag" appear in their tag list, similar to how document editors tend to name files "New Document" when no name by the user is given.

> currently the backend doesn't support multiple tags with same name. so attempting this will raise an error. that error is suppressed also (only shown in debug). which will cause the user to lose the new tag creation setup (Shorthand, Aliases, etc.).
>
> my suggestion would be to block the user from pressing done with an empty tag name and instead notify them without closing the `BuildTagPanel` window.

This is not intentional, and is currently a critical priority bug (#571). The design of this feature and PR (#591) should not have to work around this bug.

**Comment by python357-1** [comment]
I did have a thought when we were talking about it the first time, though it would take longer to implement - if we are going to allow blank tag names, have a simple confirmation modal show up when a user tries to create a tag with a blank name, that either allows them to cancel the creation of the tag or create the tag anyway.

I do agree that it would make more sense to have the text field be pre-populated with the "New Tag" text, but pre-selected so you can just begin typing the tag name when the modal shows up. There definitely are some UIs that fill in with a default name if you leave it blank (the only one I can think of right now is File Explorer), but most interfaces I can think of use the placeholder text as a way to describe what you should do with the input - like on this comment input right now, the placeholder is "Add your comment here...", but it wont make a new comment with "Add your comment here..." if I could just submit a blank comment. Most interfaces I really think hard about are web interfaces though, so I may be more biased towards that end of things.

**Comment by CyanVoxel** [comment]
Maybe I'm biased due to always quickly creating new tags for testing without much care for the name other than *something* there, but you make a good point about how something like comments here on GitHub work - or even just how many online forms operate with required fields. Doesn't need to be enforced on the db side necessarily, but some soft UI enforcement could work.

I think @VasigaranAndAngel may have been right here, for some reason I made the assumption that the "notification" would be an extra confirmation dialogue breaking the flow and slowing you down, but it really can be something as nuanced as disabling the "Done" button and displaying a little piece of red text saying that a name is required, although the later might be more involved than what @Cool-Game-Dev signed up for with #592...

**Comment by VasigaranAndAngel** [comment]
> for some reason I made the assumption that the "notification" would be an extra confirmation dialogue breaking the flow and slowing you down

What i meant by "notification" is informing the user that the tag name entry is empty. by making the border of the tag name entry field red or something like that. sorry for the confusion.

**Comment by Cool-Game-Dev** [comment]
I can try my hand at it, but just to be clear, instead of making a default "New Tag" name, we should instead disable the save button and border of the name field red while the name field is empty?

**Comment by python357-1** [comment]
Yes, also get rid of the placeholder text and put "New Tag" as the default text in the tag name box, as well as making the text highlighted by default

**Comment by Cool-Game-Dev** [comment]
Ok, I'll give it a go
